spring:
  datasource:
    # database username
    username: postgres
    # username password
    password: root
    # JDBC URL
    url: jdbc:postgresql://localhost:5432/db_api_with_jdbi3
    # JDBC driver name
    driver-class-name: org.postgresql.Driver